CREATE DATABASE WINDOWfUNCTIONS;

USE WINDOWfUNCTIONS;

CREATE TABLE STUDENT_MARKS (
  STUDENT_ID INT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  SUBJECT VARCHAR(50) NOT NULL,
  MARKS INT NOT NULL
);

INSERT INTO STUDENT_MARKS (STUDENT_ID, NAME, SUBJECT, MARKS) VALUES
  (101, 'ARJUN',  'MATHS',   95),
  (102, 'KIRAN',  'MATHS',   90),
  (103, 'NEHA',   'MATHS',   90),
  (104, 'SAI',    'MATHS',   85),
  (105, 'PRIYA',  'SCIENCE', 98),
  (106, 'AMIT',   'SCIENCE', 92),
  (107, 'RAHUL',  'SCIENCE', 92),
  (108, 'VIKAS',  'SCIENCE', 80);
  
  
  
  SELECT NAME,SUBJECT,MARKS,
  ROW_NUMBER() OVER (PARTITION BY SUBJECT)
  FROM STUDENT_MARKS;
  
  -- RANK()
  SELECT NAME,SUBJECT,MARKS,
  RANK() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) R
  FROM STUDENT_MARKS;
  
  
  -- DENSERANK()
  SELECT NAME,SUBJECT,MARKS,
  DENSE_RANK() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) DR
  FROM STUDENT_MARKS;
  
  -- PERCENTAGERANK()
  SELECT NAME,SUBJECT,MARKS,
  PERCENT_RANK() OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) PR
  FROM STUDENT_MARKS;
  
  -- NTILE
  SELECT NAME,SUBJECT,MARKS,
  NTILE(2) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) NT
  FROM STUDENT_MARKS;
  
  -- LEAD() LAG()
  SELECT NAME,SUBJECT,MARKS,
  LEAD(MARKS) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) LD,
   LAG(MARKS) OVER (PARTITION BY SUBJECT ORDER BY MARKS DESC) LG
  FROM STUDENT_MARKS;
  
  
  
  
  